name: Build and deploy PHP app to Azure Web App - bluesysapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      SYSTEM_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check composer.json
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Composer install
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_53ADF1550C244F7E8C26B817EDD291D4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DAF39391396A41DBBB2AAE493A1F4F7F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AC04617D80AB444A89FA4285FFDAEC51 }}  # Ensure this secret has 462fc2dd-a2d4-4126-b417-a495251ae8e6

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bluesysapp'
          slot-name: 'Production'
          package: .
          clean: true